#+TITLE: Emacs-KR-Wiki

* 이맥스 위키?

알고 있는 이맥스 지식을 공유하는 공간입니다.


원하는 지식을 원하는 형식으로 원하는 시간에 커밋해 주시면 됩니다.

* 어떻게 컨트리뷰션 하는가?

작성되는 글에는 지켜야할 룰이나 형식은 없습니다.


다만 이맥스에서 지원하는 노트 패키지인 org 파일 포맷으로 작성하길 적극
권장합니다. 해당 포맷으로 작성하면 깃헙 렌더링이 적용되어 웹에서 보기
좋을 뿐 아니라 이맥스에서 편집과 뷰잉이 굉장히 편리하기 때문입니다.




+이맥스 이외의 편집기로 작성하지 마십시오+ 


또한 프로젝트의 구조의 효과적 관리를 위해 아래의 룰은 지켜 작성해 주시기
바랍니다.


./packages 에는 
패키지에 대한 소개와 해당 패키지에 대한 예시 설정과 같은 것을 정리해서 올려주시면
됩니다. 패키지별 하위 디렉토리를 만들어 해당 패키지에 대한 소개, 예시
등등을 작성하시면 되겠습니다. 

예를 들어 A라는 패키지에 대해 작성하고 싶을 때 
#+BEGIN_EXAMPLE
./packages/A/A.org
#+END_EXAMPLE
와 같이 파일을 만들어 작성하시면 되겠습니다.
해당 문서에 이미지가 필요하다면 해당 폴더 내에 이미지를 추가해
사용하시면 됩니다. 원하신다면 이미지 관리용 하위폴더를 만들어
사용하셔도 됩니다.



./tutorials 에는
문자 그대로 여러가지 튜토리얼을 넣어주시면 되겠습니다. 튜토리얼은
이맥스와 관련되기만 하면 어떤 주제라도 상관없습니다. 예를 들어 이맥스를 이용해
파이썬 개발환경을 구축해 보는 튜토리얼, 이맥스 org 패키지에 대한
튜토리얼, elsip 튜토리얼과 같은 것들 말이죠.
양식은 ./packages 와 동일하게 작성해 주시면 되겠습니다.



./tips 에는 
알고있는 이맥스 관련 팁을 작성해 주시면 되겠습니다. 양식은 패키지
폴더나 튜토리얼 폴더와 동일합니다.



* 기타
  - 본 위키는 [[https://github.com/emacs-kr][emacs-kr]] 깃헙그룹에 의해 운영 및 작성되고 있습니다.
  - [[https://www.facebook.com/groups/1827603390793035/?fref=ts][AMEBA]] 그룹은 서울에서 한 달에 한번 정기 이맥스 밋업을 가지는
    오프라인 그룹입니다. [[https://github.com/emacs-kr][emacs-kr]] 을 운영하고 있는 그룹입니다. [[https://www.facebook.com/groups/1827603390793035/?fref=ts][AMEBA]]
    는 슬랙 채널이 있습니다. 초대를 원하시면 그룹 페이스북 페이지를
    참조해주세요. 슬랙 채널에선 이맥스 질답을 받고있습니다.
 
